project:
  title: "quarto-cli-7918"
  output-dir: web
  resources:
    - "pdf/*.pdf"
    - "images/*"

format:
  html:
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true